config/routes.rb
Rails.application.routes.draw do

  resources :abcs do
    collection do
      post :import
    end
  end
  resources :faros do
    collection do
      post :import
      post :price_edit
      post :price_update
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  root to: 'visitors#index'

  resources :products do
    collection do
      get :import_product
      get :syncronaize
      get :export_csv
    end
  end

  resources :viistors, only: [:index] do
    collection do
      get :manual
      get :mail_test
    end
  end

  mount ActionCable.server => '/cable'

end

app/views/shared/_errors.html.slim
- if resource.errors.present?
  .error_messages
    - resource.errors.full_messages.each do |message|
      p.error_message = message

app/views/shared/_filtersync.html.erb
<div class="dropdown">
  <% attrs = [["products_id_null", "Unsync"], ["products_id_not_null", "Sync"]] %>
  <% head = attrs.map {|attr| attr[1] if @search.send(attr[0].to_sym) }.reject(&:nil?) %>
  <button class="btn btn-outline-secondary dropdown-toggle form-control-xs" type="button" data-toggle="dropdown">
    <%= head.present? ? head.join(', ') : "Все товары" %>
  </button>
  <ul class="dropdown-menu">
    <% attrs.each do |attr| %>
      <li class="dropdown-input dropdown-item">
        <%= check_box_tag("q[#{attr[0]}]", 1, @search.send(attr[0].to_sym))%>
        <%= attr[1] %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash.html.slim
- if flash.present?
  .flash
    - flash.each do |key, message|
      p(class="#{flash_style(key)} flash-message alert-dismissible")
        = message
        button(type="button" class="close" data-dismiss="alert") &times;

app/views/shared/_header.html.slim
nav.header.d-flex.mb-1.navbar.navbar-dark.navbar-expand-lg(class="#{current_user&.admin? ? 'admin_style' : ''}")
  .logo.mr-4.pl-3.navbar-brand
    = link_to root_path do
      = image_tag 'logo.svg', data: {src: 'logo.svg'}, class: 'logo'
  button.navbar-toggler(type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation")
    span.navbar-toggler-icon
  - if user_signed_in?
    .collapse.navbar-collapse#navbarColor02
      ul.navbar-nav.mr-auto
        = render 'shared/nav_link'
      ul.navbar-nav
        li.nav-item.dropdown
          .sign_in.ml-auto.pt-3.pr-3
            - if user_signed_in?
              span.user_welcome
                - if current_user.admin?
                  strong.user_as_admin => "admin"
                span.user_email = current_user.name
            = render 'shared/sign_in'

app/views/shared/_nav_link.html.slim
li.nav-item
  = link_to 'Товары', products_path, class: 'nav-link'
ul.navbar-nav.dropdown
  li.nav-item.dropdown
    a (class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false") Поставщики
    .dropdown-menu (aria-labelledby="navbarDropdown")
      = link_to 'ABC', abcs_path, class: 'dropdown-item'
      = link_to 'Faro', faros_path, class: 'dropdown-item'
  / li.nav-item.dropdown
  /   a (class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false") Настройки
  /   .dropdown-menu (aria-labelledby="navbarDropdown")
  /     - if current_user.admin?
  /       = link_to 'Создать пользователя', new_user_registration_path, class: 'dropdown-item'

app/views/shared/_sign_in.html.slim
- if user_signed_in?
  span.ml-2 = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark btn-sm'
- else
  span.ml-2 = link_to 'Log in', new_user_session_path, class: 'btn btn-outline-success btn-sm'
  span.ml-2 = link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-info btn-sm'