config/routes.rb
Rails.application.routes.draw do

  resources :abcs do
    collection do
      post :import
    end
  end
  resources :faros do
    collection do
      post :import
      post :price_edit
      post :price_update
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  root to: 'visitors#index'

  resources :products do
    collection do
      get :import_product
      get :syncronaize
      get :export_csv
    end
  end

  resources :viistors, only: [:index] do
    collection do
      get :manual
      get :mail_test
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/abc.rb
class Abc < ApplicationRecord
  has_one :product
  scope :product_all_size, -> { order(:id).size }
end

app/models/faro.rb
class Faro < ApplicationRecord
  has_many :products
  scope :product_all_size, -> { order(:id).size }
end

app/controllers/abcs_controller.rb
class AbcsController < ApplicationController
  include Distributor
  
  before_action :set_abc, only: [:show]
  
  def show; end

  def update
    @abc = Abc.find(params[:id])

    respond_to do |format|
      if @abc.update(abc_params)
        format.html { redirect_to(@abc, :notice => 'ABC was successfully updated.') }
        format.json { respond_with_bip(@abc) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@abc) }
      end
    end
  end

  def import
    ActionCable.server.broadcast 'status_process', {distributor: "abc", process: "update_distributor", status: "start", message: "Обновление товаров поставщика Abc"}

    FileUtils.rm_rf(Dir.glob('provider/*.*'))
    uploaded_io = params[:file]

    File.open(Rails.root.join('provider', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    path_file = Rails.root.join('provider', uploaded_io.original_filename).to_s
    extend_file = uploaded_io.original_filename.to_s
    AbcImportJob.perform_later(path_file, extend_file)
    # flash[:notice] = 'Задача импорта Товаров запущена'
    # redirect_to abcs_path
  end

  private

  def set_abc
    @abc = Abc.find(params[:id])
  end

  def abc_params
    params.require(:abc).permit(:price, :quantity)
  end
end

app/helpers/abcs_helper.rb
module AbcsHelper
end

app/views/abcs/edit.html.erb
<h1>Abcs#edit</h1>
<p>Find me in app/views/abcs/edit.html.erb</p>

app/views/abcs/index.html.erb
<div class="row mb-2 mr-0 ml-0 align-items-center" id="filter_menu">
  <h3 class="mr-2">Поставщик ABC</h3>
  <div class="col- mr-1">
    <div class="form-import">
      <%= form_tag import_abcs_path, remote: true, multipart: true, class: "form_import" do %>
        <%= file_field_tag :file, class: "form-control-xs" %>
        <%= submit_tag "Import" , class:'btn btn-primary btn-sm form-control-xs', disabled: true %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 mr-1">
    <span class="align-middle"><small>Всего: <%= Abc.product_all_size %></small></span>
    <span class="align-middle"><small>Отфильтровано: <%=@abcs.count%></small></span><br>
    <span class="align-middle"><small>Больше нуля: <%= Abc.where.not(quantity: 0).size %></small></span>
<!--    <span class="align-middle"><small>Синхронизируется: <%#= Product.where.not(abc: nil).size %></small></span>-->

  </div>
<!--  <div class="col- mr-1">-->
<!--    <div class="dropdown">-->
<!--      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--        Действия-->
<!--      </a>-->
<!--      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">-->
        <%#= link_to 'Парсинг', parsing_lit_koms_path, class: 'dropdown-item'%>
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
  <!--  <div class="col- mr-1">-->
  <%#= link_to '<span class="oi oi-pencil"></span>'.html_safe, edit_multiple_products_path, class: 'btn btn-secondary', id: 'edit_multiple', remote: true, data: { toggle: 'modal', 'target': '#modal-edit' } %>
  <%#= link_to '<span class="oi oi-trash"></span>'.html_safe, delete_selected_products_path, class: 'btn btn-secondary', id: 'deleteAll', remote: true%>
  <!--  </div>-->
<!--  <div class="col- ">-->
    <%= search_form_for @search, html: {class: 'form-inline'}  do |f|%>
      <%= f.search_field :id_eq, placeholder: 'ID', class: "form-control form-control-xs"%>
      <%= f.search_field :title_or_sku_cont, placeholder: 'Название, Артикул', class: "form-control form-control-xs"%>
      <%= f.collection_select :brand_eq, Abc.all.order('brand ASC').map {|product| [product.brand, product.brand]}.uniq, :first, :last, {include_blank: "Бренд"}, class: "form-control form-control-xs" , style: "max-width: 150px;" %>
      <%= f.collection_select :series_eq, Abc.all.order('series ASC').map {|product| [product.series, product.series]}.uniq, :first, :last, {include_blank: "Серия"}, class: "form-control form-control-xs" , style: "max-width: 150px;" %>
      <%= f.search_field :quantity_eq, placeholder: 'остаток', class: "form-control form-control-xs"%>
      <%#= f.collection_select :quantity_eq, [[0, 0], [10, 10]], :first, :last, {include_blank: "Остаток"}, class: "form-control form-control-xs", style: "width: 120px;" %>
      <div class="form-group ml-2 button_group">
        <%= f.search_field :price_gteq, placeholder: 'Цена от', class: "form-control form-control-xs mr-2"%>
        <%= f.search_field :price_lteq, placeholder: 'Цена до', class: "form-control form-control-xs"%>
      </div>

      <%= render 'shared/filtersync', f: f %>

      <div class="form-group ml-2 button_group">
        <% f.submit 'Поиск', class: 'btn btn-info' %>
        <%= button_tag(type: 'submit', :class => "btn btn-info form-control-xs") do %><span class="oi oi-magnifying-glass"></span><% end %>
        <%= link_to '<span class="oi oi-reload"></span>'.html_safe, abcs_path, class: 'btn btn-outline-dark form-control-xs' %>
        <%= link_to '<span class="oi oi-list"></span>'.html_safe, abcs_path(otchet_type: 'selected', q: @params_q_to_csv), title: "Создать файл с выбранными товарами", class: 'btn btn-outline-dark form-control-xs'%>
      </div>
    <% end %>
  </div>

<div class="table-responsive" id="container_for_table_with_data">
  <table class="table table-hover table-condensed table-sm">
    <thead class="thead-light">
    <tr>
<!--      <th><%#= check_box_tag 'selectAll', value = 'selectAll'%></th>-->
      <th>ID</th>
      <th>ID в Товарах</th>
      <th>Артикул</th>
      <th>Название</th>
      <th>Актуальность</th>
      <th><%= sort_link(@search, :quantity) %></th>
      <th><%= sort_link(@search, :price) %></th>
      <th>Бренд</th>
      <th>Серия</th>
    </tr>
    </thead>

    <tbody id="products_table">
    <% @abcs.each do |product| %>
      <tr class="<%= 'sync' if product.products.present? %>">
<!--        <td><%#=check_box_tag "product_ids[]", product.id%></td>-->
        <td><%= product.id %></td>
        <td>
          <% product.products.each do |product| %>
            <%= link_to product.id, products_path(q: {id_eq: product.id}) %>
          <% end %>
        </td>
        <td><%= product.sku %></td>
        <td><%= link_to product.title, product, target: '_blank' %></td>
        <td><%= product.check %></td>
        <td><%= best_in_place product, :quantity, :as => :input %></td>
        <td><%= best_in_place product, :price, :as => :input %></td>
        <td><%= product.brand %></td>
        <td><%= product.series %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="digg_pagination mt-4 mb-4">
  <%= will_paginate @abcs %>
</div>

app/views/abcs/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @abc.title %>
</p>

<p>
  <strong>Артикул:</strong>
  <%= @abc.sku %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @abc.price %>
</p>

<p>
  <strong>Цена закупки:</strong>
  <%= @abc.purchase_price %>
</p>

<p>
  <strong>Количество:</strong>
  <%= @abc.quantity %>
</p>

<p>
  <strong>Бренд:</strong>
  <%= @abc.brand %>
</p>

<p>
  <strong>Серия:</strong>
  <%= @abc.series %>
</p>

<p>
  <strong>Check:</strong>
  <%= @abc.check %>
</p>

<%= link_to 'Back', abcs_path %>

app/views/abcs/update.html.erb
<h1>Abcs#update</h1>
<p>Find me in app/views/abcs/update.html.erb</p>