config/routes.rb
Rails.application.routes.draw do

  resources :abcs do
    collection do
      post :import
    end
  end
  resources :faros do
    collection do
      post :import
      post :price_edit
      post :price_update
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  root to: 'visitors#index'

  resources :products do
    collection do
      get :import_product
      get :syncronaize
      get :export_csv
    end
  end

  resources :viistors, only: [:index] do
    collection do
      get :manual
      get :mail_test
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/faro.rb
class Faro < ApplicationRecord
  has_many :products
  scope :product_all_size, -> { order(:id).size }
end

app/controllers/faros_controller.rb
class FarosController < ApplicationController
  include Distributor

  # before_action :set_faro, only: [:show]

  def show; end

  def update
    @faro = Faro.find(params[:id])

    respond_to do |format|
      if @faro.update(abc_params)
        format.html { redirect_to(@faro, :notice => 'Faro was successfully updated.') }
        format.json { respond_with_bip(@faro) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@faro) }
      end
    end
  end

  def import
    ActionCable.server.broadcast 'status_process', {distributor: "faro", process: "update_distributor", status: "start", message: "Обновление товаров поставщика Faro"}

    FileUtils.rm_rf(Dir.glob('public/faro/*.*'))
    uploaded_io = params[:file]

    File.open(Rails.root.join('public', 'faro', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    path_file = Rails.root.join('public', 'faro', uploaded_io.original_filename).to_s
    extend_file = uploaded_io.original_filename.to_s
    FaroImportJob.perform_later(path_file, extend_file)
    flash[:notice] = 'Задача импорта Товаров запущена'
    redirect_to faros_path
  end

  def price_edit
    if params[:ids].present?
      @faros = Faro.find(params[:ids])
      respond_to do |format|
        format.js
      end
    else
      redirect_to faros_path
    end
  end

  def price_update
    faros = Faro.find(params[:ids])
    price_move = params[:product_price][:price_move]
    price_shift = params[:product_price][:price_shift]
    price_points = params[:product_price][:price_points]

    faros.each do |faro|
      salePrice = faro.price.present? ? faro.price : 0
      price_shift = price_shift.to_f
      if price_points == "fixed"
        new_price = (salePrice.send(price_move, price_shift)).round
      else
        new_price = (salePrice.send(price_move, price_shift*0.01*salePrice)).round
      end
      faro.update(price: new_price)
    end
    redirect_to faros_path
  end

  private

  def set_faro
    @faro = Faro.find(params[:id])
  end

  def faro_params
    params.require(:faro).permit(:price, :quantity)
  end
end

app/helpers/faros_helper.rb
module FarosHelper
end

app/views/faros/_price_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="priceEdit">Обновление цен.</h4>
      <small>Выбрано: <%=@faros.size%></small>
      <button type="button" class="close" data-dismiss="modal">&#x2715</button>
    </div>
    <div class="form-group"><label class="col-sm-12 control-label">Новое значение</label></div>
    <%= form_tag price_update_faros_path, method: :post , class: "form-inline" do %>

      <div class="modal-body">
        <%@faros.each do |pr|%>
          <%= hidden_field_tag "ids[]", pr.id %>
        <% end %>

        <%= fields_for :product_price do |f| %>
          <div class="form-group">
            <%= f.select :price_move, [['+','+'], ['-','-']], {:include_blank => false}, {class: "form-control"} %>
            <%= f.text_field :price_shift, {type: "number", class: "form-control"} %>
            <%= f.select :price_points, [['%','percents'], ['ед.','fixed']], {:include_blank => false}, {class: "form-control"} %>
          </div>
        <% end %>
      </div>

      <div class="modal-footer">
        <%= submit_tag "Обновить", class: "btn btn-primary" %>
<!--        <button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>-->
      </div>
    <% end %>
  </div>
</div>

app/views/faros/edit.html.erb
<h1>Faros#edit</h1>
<p>Find me in app/views/faros/edit.html.erb</p>

app/views/faros/index.html.erb
<div class="row mb-2 mr-0 ml-0 align-items-center" id="filter_menu">
  <h3 class="mr-2">Поставщик Faro</h3>
  <div class="col- mr-1">
    <div class="form-import">
      <%= form_tag import_faros_path, remote: true, multipart: true, class: "form_import" do %>
        <%= file_field_tag :file, class: "form-control-xs" %>
        <%= submit_tag "Import" , class:'btn btn-primary btn-sm form-control-xs', disabled: true %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 mr-1">
    <span class="align-middle"><small>Всего: <%= Faro.product_all_size %></small></span>
    <span class="align-middle"><small>Отфильтровано: <%=@faros.count%></small></span><br>
    <span class="align-middle"><small>Больше нуля: <%= Faro.where.not(quantity: 0).size %></small></span>
<!--    <span class="align-middle"><small>Синхронизируется: <%#= Product.where.not(abc: nil).size %></small></span>-->

  </div>
  <div class="col-">
    <div class="col- ">
      <div class="dropdown">
        <a class="btn btn-info dropdown-toggle form-control-xs" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Действия
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to "Редактировать цены",
                      price_edit_faros_path,
                      remote: true,
                      class: "dropdown-item form-control-xs",
                      id: "faro_price_edit_button",
                      data: {type: :js},
                      method: :post
          %>
        </div>
      </div>
    </div>
  </div>
    <%= search_form_for @search, html: {class: 'form-inline'}  do |f|%>
      <%= f.search_field :id_eq, placeholder: 'ID', class: "form-control form-control-xs"%>
      <%= f.search_field :title_or_sku_cont, placeholder: 'Название, Артикул', class: "form-control form-control-xs"%>
      <%= f.collection_select :brand_eq, Faro.all.order('brand ASC').map {|product| [product.brand, product.brand]}.uniq, :first, :last, {include_blank: "Бренд"}, class: "form-control form-control-xs" , style: "max-width: 150px;" %>
      <%= f.search_field :quantity_eq, placeholder: 'остаток', class: "form-control form-control-xs"%>
      <%#= f.collection_select :quantity_eq, [[0, 0], [10, 10]], :first, :last, {include_blank: "Остаток"}, class: "form-control form-control-xs", style: "width: 120px;" %>
      <div class="form-group ml-2 button_group">
        <%= f.search_field :price_gteq, placeholder: 'Цена от', class: "form-control form-control-xs mr-2"%>
        <%= f.search_field :price_lteq, placeholder: 'Цена до', class: "form-control form-control-xs"%>
      </div>

      <%= render 'shared/filtersync', f: f %>

      <div class="form-group ml-2 button_group">
        <% f.submit 'Поиск', class: 'btn btn-info' %>
        <%= button_tag(type: 'submit', :class => "btn btn-info form-control-xs") do %><span class="oi oi-magnifying-glass"></span><% end %>
        <%= link_to '<span class="oi oi-reload"></span>'.html_safe, faros_path, class: 'btn btn-outline-dark form-control-xs' %>
        <%= link_to '<span class="oi oi-list"></span>'.html_safe, faros_path(otchet_type: 'selected', q: @params_q_to_csv), title: "Создать файл с выбранными товарами", class: 'btn btn-outline-dark form-control-xs'%>
      </div>
    <% end %>
  </div>

<div class="table-responsive" id="container_for_table_with_data">
  <table class="table table-hover table-condensed table-sm">
    <thead class="thead-light">
    <tr>
      <th><%= check_box_tag 'selectAll', value = 'selectAll'%></th>
      <th>ID</th>
      <th>ID в Товарах</th>
      <th>Артикул</th>
      <th>Название</th>
      <th>Актуальность</th>
      <th><%= sort_link(@search, :quantity) %></th>
      <th><%= sort_link(@search, :price) %></th>
      <th><%= sort_link(@search, :purchase_price, 'Закупочная цена') %></th>
      <th>Бренд</th>
    </tr>
    </thead>

    <tbody id="products_table">
    <% @faros.each do |product| %>
      <tr class="<%= 'sync' if product.products.present? %>">
        <td><%=check_box_tag "product_ids[]", product.id%></td>
        <td><%= product.id %></td>
        <td>
          <% product.products.each do |product| %>
            <%= link_to product.id, products_path(q: {id_eq: product.id}) %>
          <% end %>
        </td>
        <td><%= product.sku %></td>
        <td><%= link_to product.title, product, target: '_blank' %></td>
        <td><%= product.check %></td>
        <td><%= best_in_place product, :quantity, :as => :input %></td>
        <td><%= best_in_place product, :price, :as => :input %></td>
        <td><%= product.purchase_price %></td>
        <td><%= product.brand %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="digg_pagination mt-4 mb-4">
  <%= will_paginate @faros %>
</div>

app/views/faros/price_edit.js.erb
$("#modalPriceEdit").html('<%= j render 'price_edit' %>');

app/views/faros/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @faro.title %>
</p>

<p>
  <strong>Артикул:</strong>
  <%= @faro.sku %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @faro.price %>
</p>

<p>
  <strong>Цена закупки:</strong>
  <%= @faro.purchase_price %>
</p>

<p>
  <strong>Количество:</strong>
  <%= @faro.quantity %>
</p>

<p>
  <strong>Бренд:</strong>
  <%= @faro.brand %>
</p>

<p>
  <strong>Check:</strong>
  <%= @faro.check %>
</p>

<%= link_to 'Back', faros_path %>

app/views/faros/update.html.erb
<h1>Faros#update</h1>
<p>Find me in app/views/faros/update.html.erb</p>