config/routes.rb
Rails.application.routes.draw do

  resources :abcs do
    collection do
      post :import
    end
  end
  resources :faros do
    collection do
      post :import
      post :price_edit
      post :price_update
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  root to: 'visitors#index'

  resources :products do
    collection do
      get :import_product
      get :syncronaize
      get :export_csv
    end
  end

  resources :viistors, only: [:index] do
    collection do
      get :manual
      get :mail_test
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/faro.rb
class Faro < ApplicationRecord
  has_many :products
  scope :product_all_size, -> { order(:id).size }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :abc, optional: true
  belongs_to :faro, optional: true

  scope :product_all_size, -> { order(:id).size }
  scope :product_qt_not_null, -> { where('quantity > 0') }
  scope :product_qt_not_null_size, -> { where('quantity > 0').size }
  scope :product_cat, -> { order('cat DESC').select(:cat).uniq }
  scope :product_image_nil, -> { where(image: [nil, '']).order(:id) }

  DISTRIBUTOR = [
    ["faro_id_not_null", "Faro"],
    ["abc_id_not_null", "ABC"],
    ["abc_id_and_faro_id_null", "Unsync"],
    ["abc_id_or_faro_id_not_null", "Sync"],
  ]

  validate :new_distributor_empty, on: :update

  def new_distributor_empty
    if abc_id.present?
      abc = Abc.find_by(id: abc_id)
      if abc.nil?
        errors.add(:abc_id, "Товар поставщика не существует")
      end
    end
    if faro_id.present?
      faro = Faro.find_by(id: faro_id)
      if faro.nil?
        errors.add(:faro_id, "Товар поставщика не существует")
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy, :show]

  def index
    if params[:q]
      @params = params[:q]
      # @params[:combinator] = 'or'

      @params.delete(:abc_id_not_null) if @params[:abc_id_not_null] == '0'
      @params.delete(:abc_id_null) if @params[:abc_id_null] == '0'

      # делаем доступные параметры фильтров, чтобы их поместить их в параметр q «кнопки создать csv по фильтру»
      @params_q_to_csv = @params.permit(:sku_or_title_cont,
                                        :distributor_eq,
                                        :quantity_eq,
                                        :price_gteq,
                                        :price_lteq,
                                        :abc_id_eq,
                                        :faro_id_eq,
                                        :abc_id_or_faro_id_not_null,
                                        :abc_id_and_faro_id__null,
      )
    else
      @params = []
    end

    @search = Product.ransack(@params)
    @search.sorts = 'id desc' if @search.sorts.empty?

    # данные для «кнопки создать csv по фильтру», все данные в отличии от @products, который ограничен 100
    @search_id_by_q = Product.ransack(@params_q_to_csv).result.pluck(:id)

    @products = @search.result.paginate(page: params[:page], per_page: 100)

    if params['otchet_type'] == 'selected'
      Services::CsvSelected.call(@search_id_by_q)
      redirect_to '/product_selected.csv'
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.json { respond_with_bip(@product) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@product) }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { render json: { title: @product.title }, status: :ok }
      format.js
    end
  end

  def import_product
    ActionCable.server.broadcast 'status_process', {distributor: "product", process: "update_product", status: "start", message: "Обновление товаров из InSales"}

    ImportProductJob.perform_later
    # redirect_to products_path, notice: 'Запущен процесс Обновление Товаров InSales'
  end

  def syncronaize
    ActionCable.server.broadcast 'status_process', {distributor: "product", process: "syncronize", status: "start", message: "Синхронизация остатков и цен"}

    SyncronaizeJob.perform_later
    # flash[:notice] = 'Задача синхронизации каталога запущена'
    # redirect_to products_path
  end

  def export_csv
    ActionCable.server.broadcast 'status_process', {distributor: "product", process: "export_csv", status: "start", message: "Создание Csv-файла для экспорта"}

    ExportCsvJob.perform_later
    # flash[:notice] = 'Задача создания CSV для экспорта запущена'
    # redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:sku, :title, :desc, :cat, :oldprice, :price, :quantity, :image, :url, :abc_id, :faro_id)
  end
end

app/helpers/products_helper.rb
# TODO NewDistributor
module ProductsHelper
  def distributor_exist?(product)
    true if product.abc.present? ||
      product.faro.present?
  end

  def count_product_var(product)
    variants = Product.where(insales_id: product.insales_id).order("id DESC")
    count = variants.size
    index_var = 0
    variants.each_with_index do |variant, index|
      index_var = index if variant.insales_var_id == product.insales_var_id
    end
    {count: count, index_var: index_var + 1 }
  end

  def color_by_id(id)
    # color_id = id.to_s.split('').last
    color_id = id.to_s[/\d{2}$/]
    colors = {"0"=>"Aqua", "01"=>"Black", "02"=>"BlanchedAlmond", "03"=>"Blue", "04"=>"BlueViolet", "05"=>"Brown", "06"=>"BurlyWood", "07"=>"CadetBlue", "08"=>"Chartreuse", "09"=>"Chocolate", "10"=>"Coral",
              "11"=>"CornflowerBlue", "12"=>"Crimson", "13"=>"Cyan", "14"=>"DarkBlue", "15"=>"DarkCyan", "16"=>"DarkGoldenRod", "17"=>"DarkGreen", "18"=>"DarkGrey", "19"=>"DarkKhaki", "20"=>"DarkMagenta",
              "21"=>"DarkOliveGreen", "22"=>"DarkOrange", "23"=>"DarkRed", "24"=>"DarkSalmon", "25"=>"DarkSeaGreen", "26"=>"DarkSlateBlue", "27"=>"DarkSlateGrey", "28"=>"DarkTurquoise", "29"=>"DarkViolet", "30"=>"DeepPink",
              "31"=>"DeepSkyBlue", "32"=>"DimGrey", "33"=>"DodgerBlue", "34"=>"FireBrick", "35"=>"Fuchsia", "36"=>"Gold", "37"=>"Goldenrod", "38"=>"Gray", "39"=>"Green", "40"=>"GreenYellow",
              "41"=>"HotPink", "42"=>"IndianRed", "43"=>"Indigo", "44"=>"Khaki", "45"=>"LightBlue", "46"=>"LightCoral", "47"=>"LightGreen", "48"=>"LightPink", "49"=>"LightSalmon", "50"=>"LightSeaGreen",
              "51"=>"LightSkyBlue", "52"=>"LightSlateGrey", "53"=>"Lime", "54"=>"LimeGreen", "55"=>"Magenta", "56"=>"YellowGreen", "57"=>"MediumAquaMarine", "58"=>"MediumBlue", "59"=>"MediumOrchid", "60"=>"MediumPurple",
              "61"=>"MediumSeaGreen", "62"=>"MediumSlateBlue", "63"=>"MediumSpringGreen", "64"=>"MediumTurquoise", "65"=>"MediumVioletRed", "66"=>"Navy", "67"=>"Olive", "68"=>"OliveDrab", "69"=>"Orange", "70"=>"OrangeRed",
              "71"=>"Orchid", "72"=>"PaleGreen", "73"=>"PaleTurquoise", "74"=>"PaleVioletRed", "75"=>"Peru", "76"=>"Pink", "77"=>"Plum", "78"=>"Purple", "79"=>"RebeccaPurple", "80"=>"Red",
              "81"=>"RosyBrown", "82"=>"RoyalBlue", "83"=>"SaddleBrown", "84"=>"Salmon", "85"=>"SandyBrown", "86"=>"SeaGreen", "87"=>"Sienna", "88"=>"SkyBlue", "89"=>"SlateBlue", "90"=>"SlateGrey",
              "91"=>"SpringGreen", "92"=>"SteelBlue", "93"=>"Tan", "94"=>"Teal", "95"=>"Thistle", "96"=>"Tomato", "97"=>"Turquoise", "98"=>"Violet", "99"=>"Wheat", "100"=>"Yellow", "101"=>"Maroon"}

    colors[color_id]
  end
end

app/views/products/_distributor_abc.erb
<% if product.abc.present? %>
  <p>ID: <strong><%= best_in_place product, :abc_id, :as => :input %></strong><br>остаток: <%= product.abc&.quantity %><br>цена: <%= product.abc&.price %></p>
<% else %>
  <p>ID: <%= best_in_place product, :abc_id, :as => :input %></p>
<% end %>

app/views/products/_distributor_faro.erb
<% if product.faro.present? %>
  <p>ID: <strong><%= best_in_place product, :faro_id, :as => :input %></strong><br>остаток: <%= product.faro&.quantity %><br>цена: <%= product.faro&.price %></p>
<% else %>
  <p>ID: <%= best_in_place product, :faro_id, :as => :input %></p>
<% end %>

app/views/products/_form.html.slim
= form_with model:@product, local: true do |f|
  = render "shared/errors", resource: @product

  .form-inputs
    .row
      span.col-md-5
        | Название: 
        strong = @product.title

      span.col-md-5
        | Артикул Товара в InSales:
        strong = @product.sku

      span.col-md-5
        | ID в InSales:
        strong = @product.insales_id

      span.col-md-5
        | ID Варианта в InSales:
        strong = @product.insales_var_id


      span.col-md-5
        = f.label 'Цена продажи:'
        = f.text_field :price

      span.col-md-4
        = f.label 'Остаток:'
        = f.text_field :quantity

      span.col-12
        span.editable
          = f.label "ID у поставщика ABC"
          = f.text_field :abc_id

    span.col-12 Описание: #{@product.desc.truncate(300)}

    span.col-12
      | Категория:
      strong =@product.cat

    - if @product.url.present?
      .col-md-2
        = link_to 'Товар в InSales', @product.url , class: "d-flex align-items-center", target: 'blank'

  - if @product.image.present?
    .row.ml-0.mr-0
      - @product.image.split(' ').each do |pict|
        .w-25
          img.img-fluid.img-thumbnail src="#{pict}"

  .form-actions.mt-4
    = f.button :submit , class: "btn btn-outline-success"
    = link_to 'Back', products_path, class: "btn btn-outline-secondary"

app/views/products/edit.html.slim
h3 Редактирование Товара

= render 'form', product: @product

/ = link_to 'Show', @product
/ = link_to 'Back', products_path

app/views/products/index.html.erb
<div class="row mb-1 mr-0 ml-0 align-items-center" id="filter_menu">
  <h3 class="mr-2 ">Товары</h3>
  <div class="col-md-4 ">
    <div class="mr-1">
      <span class="align-middle"><small>Всего: <%= Product.product_all_size %></small></span>
      <span class="align-middle"><small>Отфильтровано: <%=@products.count%></small></span>
      <span class="align-middle"><small>Больше 0: <%= Product.product_qt_not_null_size %></small></span>
    </div>
  </div>
  <div class="col-">
    <div class="col- ">
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle form-control-xs" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Действия
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Обновить каталог Товаров', import_product_products_path, remote: true, class: 'dropdown-item'%>
          <%#= link_to 'Линковать ()', linking_products_path, class: 'dropdown-item'%>
          <%= link_to 'Синхронизировать Цены и Остатки', syncronaize_products_path, remote: true, class: 'dropdown-item'%>
          <%= link_to 'Создать CSV-файл для экспорта', export_csv_products_path, remote: true, class: 'dropdown-item'%>
          <%= link_to 'Скачать CSV-файл для экспорта', "/export_insales.csv", class: 'dropdown-item' %>
          <%#= link_to 'Создать CSV-файл с товарами без Артикула', csv_not_sku_products_path, class: 'dropdown-item'%>
<!--                <div class="dropdown-divider"></div>-->
          <%#= link_to '(Скачать CSV-файл для экспорта)', "/export_insales.csv", class: 'dropdown-item' %>
          <%#= link_to '(Скачать CSV-файл с товарами без Артикула)', "/csv_not_sku.csv", class: 'dropdown-item' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col- ">
    <%= search_form_for @search, html: {class: 'form-inline'}  do |f|%>
      <%= f.search_field :sku_or_title_cont, placeholder: 'Артикул, Название', class: "form-control form-control-xs"%>
      <%= f.collection_select :distributor_eq, Product.all.order('distributor ASC').map {|product| [product.distributor, product.distributor]}.uniq, :first, :last, {include_blank: "Производитель"}, class: "form-control form-control-xs" , style: "max-width: 150px;" %>
      <%= f.collection_select :quantity_eq, [[0, 0], [10, 10]], :first, :last, {include_blank: "Остаток"}, class: "form-control form-control-xs", style: "width: 120px;" %>
      <%= f.search_field :abc_id_eq, placeholder: 'ID продукта поставщика', class: "form-control form-control-xs" %>
      <div class="form-group button_group">
        <%= f.search_field :price_gteq, placeholder: 'Цена от', class: "form-control form-control-xs"%>
        <%= f.search_field :price_lteq, placeholder: 'Цена до', class: "form-control form-control-xs"%>
      </div>

      <div class="dropdown">
        <% head = Product::DISTRIBUTOR.map {|attr| attr[1] if @search.send(attr[0].to_sym) }.reject(&:nil?) %>
        <button class="btn btn-outline-secondary dropdown-toggle form-control-xs" type="button" data-toggle="dropdown">
          <%= head.present? ? head.join(', ') : "Поставщики" %>
        </button>
        <ul class="dropdown-menu">
          <% Product::DISTRIBUTOR.each do |attr| %>
            <li class="dropdown-input dropdown-item<%= ' sync_unsync' if attr[1] == 'Sync' || attr[1] == 'Unsync' %>">
              <%= check_box_tag("q[#{attr[0]}]", 1, @search.send(attr[0].to_sym))%>
              <%= content_tag :span, attr[1] %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="form-group ml-2 button_group">
        <% f.submit 'Поиск', class: 'btn btn-info' %>
        <%= button_tag(type: 'submit', :class => "btn btn-info form-control-xs") do %>
          <span class="oi oi-magnifying-glass"></span>
        <% end %>
        <%= link_to '<span class="oi oi-reload"></span>'.html_safe, products_path, class: 'btn btn-outline-dark form-control-xs' %>
        <%= link_to '<span class="oi oi-list"></span>'.html_safe, products_path(otchet_type: 'selected', q: @params_q_to_csv), title: "Создать файл с выбранными товарами", class: 'btn btn-outline-dark form-control-xs'%>
      </div>
    <% end %>
  </div>
</div>

<div class="table-responsive" id="container_for_table_with_data">
<table class="table table-hover table-condensed table-sm">
  <thead class="thead-light">
    <tr>
<!--      <th>-->
        <%#= link_to '<span class="oi oi-trash"></span>'.html_safe, delete_selected_products_path, remote: true, class: "btn btn-danger btn-sm", id: "deleteAll" %>
        <%#= check_box_tag 'selectAll', value = 'selectAll'%>
<!--      </th>-->
      <th>Артикул</th>
      <th>ID</th>
      <th style="width:250px;">Title</th>
      <th><%= sort_link(@search, :price) %></th>
      <th><%= sort_link(@search, :quantity) %></th>
      <th>Производитель</th>
      <th>ABC</th>
      <th>Faro</th>
<!--      <th>Desc</th>-->
      <th>Параметры</th>
      <th style="width:250px;">Image</th>
      <th>Товар в InSales</th>
<!--      <th>Товар у поставщика</th>-->
      <th></th>
    </tr>
  </thead>

  <tbody id="products_table">
    <% @products.each do |product| %>
      <tr class="<%= 'sync' if distributor_exist?(product) %>" id='<%= "product_id_#{product.id}" %>'>
<!--        <td>-->
          <%#=check_box_tag "product_ids[]", product.id%>
<!--        </td>-->
        <td>
          <%= product.sku %>
        </td>
        <td>
          <%= product.id %>
          <% count_var = count_product_var(product) %>
          <% if count_var[:count] > 1 %>
            <span class="product__count_product_var" style="background-color: <%= color_by_id(product.insales_id) %>">
              <%= count_var[:index_var] %><br>(<%= count_var[:count] %>)
            </span>
          <% end %>
        </td>
        <td><%= link_to product.title, edit_product_path(product) %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.distributor %></td>
        <td>
          <%= render 'distributor_abc', product: product %>
        </td>
        <td>
          <%= render 'distributor_faro', product: product %>
        </td>
<!--        <td><%#= product.desc.truncate(25) if product.desc != nil%></td>-->
        <td><%= product.p1.gsub(" --- ", ", ") %></td>
        <td class="row ml-0 mr-0">
          <% if product.image.present? %>
            <% product.image.split(' ').each do |pict| %>
              <div class="w-25">
                <img class="img-thumbnail" src="<%= pict %>">
              </div>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Ссылка', product.url , target: 'blank' %></td>
<!--        <td>-->
          <%# if product.abc.present? %>
              <%#= link_to '<span class="oi oi-eye"></span> ABC'.html_safe, product.abc.link , target: 'blank' %>
          <%#end%>
<!--        </td>-->
        <td><%= link_to '<span class="oi oi-trash"></span>'.html_safe, product, method: :delete, data: { type: :json, confirm: "Удалить? #{product.title}" }, remote: true, class: "delete_product" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="digg_pagination mt-4 mb-4">
    <%= will_paginate @products %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @product.desc %>
</p>

<p>
  <strong>Cat:</strong>
  <%= @product.cat %>
</p>

<p>
  <strong>Charact:</strong>
  <%= @product.p1 %>
</p>


<p>
  <strong>Oldprice:</strong>
  <%= @product.oldprice %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Картинки:</strong>
  <% @product.image.split(' ').each do |image| %>
    <%= image_tag image%>
  <% end %>
</p>

<p>
  <strong>Url:</strong>
  <%= @product.url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>